server:
  port: 8083
  servlet:
    context-path: /corebanking
spring:
  application:
    name: corebanking-service
  datasource:
    url: jdbc:mysql://localhost:3307/coredb
    username: root
<<<<<<< HEAD
    password: 22572
=======
    password: 0986341885dai
    driver-class-name: com.mysql.cj.jdbc.Driver
>>>>>>> daile-dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/myrealm

#Dubbo
dubbo:
  application:
    name: corebanking-service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.corebanking_service.service
