server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/myrealm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename:
      - i18n/messages
    encoding: UTF-8
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${DOCKER_HOST:localhost}:9094
      bindings:
        mail-out-0:
          destination: send-mail-html
          content-type: application/json
dubbo:
  application:
    qos-enable: true
    qos-port: 22225
    name: account-service
    qos-port: 22291
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.account_service.service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
