server:
  port: 8082
  servlet:
    context-path: /account

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/myrealm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename:
      - i18n/messages
    encoding: UTF-8

dubbo:
  application:
    name: "account-service"
    qos-enable: false
    metadata-type: remote
    serialize-check-status: STRICT
    serialization:
      security:
        check: true
      # Trỏ đến file allowlist của bạn
        allowlist: "file:security/serialize.allowlist"
  protocol:
    name: "dubbo"
    port: -1
  registry:
    address: "zookeeper://${DOCKER_HOST:localhost}:2181"

