server:
  port: 8082
  servlet:
    context-path: /account

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/myrealm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename:
      - i18n/messages
    encoding: UTF-8
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${DOCKER_HOST:localhost}:9094
      bindings:
        mail-out-0:
          destination: send-mail-html
          content-type: application/json
  data:
      redis:
        host: localhost
        port: 6379

# Core Banking Service Configuration
core-banking:
  base-url: http://localhost:8083/corebanking

dubbo:
  provider:
    filter: -contextHolderAuthenticationResolverFilter
  consumer:
    filter: -contextHolderAuthenticationResolverFilter
  application:
    name: account-service
    qos-enable: false
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.example.account_service.service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html